//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//


package simplenlg.xmlrealiser.wrapper;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the simplenlg.xmlrealiser.wrapper package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: simplenlg.xmlrealiser.wrapper
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NLGSpec }
     * 
     */
    public NLGSpec createNLGSpec() {
        return new NLGSpec();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link RecordSet }
     * 
     */
    public RecordSet createRecordSet() {
        return new RecordSet();
    }

    /**
     * Create an instance of {@link XmlPPPhraseSpec }
     * 
     */
    public XmlPPPhraseSpec createXmlPPPhraseSpec() {
        return new XmlPPPhraseSpec();
    }

    /**
     * Create an instance of {@link XmlAdjPhraseSpec }
     * 
     */
    public XmlAdjPhraseSpec createXmlAdjPhraseSpec() {
        return new XmlAdjPhraseSpec();
    }

    /**
     * Create an instance of {@link XmlDocumentElement }
     * 
     */
    public XmlDocumentElement createXmlDocumentElement() {
        return new XmlDocumentElement();
    }

    /**
     * Create an instance of {@link XmlWordElement }
     * 
     */
    public XmlWordElement createXmlWordElement() {
        return new XmlWordElement();
    }

    /**
     * Create an instance of {@link XmlAdvPhraseSpec }
     * 
     */
    public XmlAdvPhraseSpec createXmlAdvPhraseSpec() {
        return new XmlAdvPhraseSpec();
    }

    /**
     * Create an instance of {@link XmlCoordinatedPhraseElement }
     * 
     */
    public XmlCoordinatedPhraseElement createXmlCoordinatedPhraseElement() {
        return new XmlCoordinatedPhraseElement();
    }

    /**
     * Create an instance of {@link XmlNPPhraseSpec }
     * 
     */
    public XmlNPPhraseSpec createXmlNPPhraseSpec() {
        return new XmlNPPhraseSpec();
    }

    /**
     * Create an instance of {@link DocumentRealisation }
     * 
     */
    public DocumentRealisation createDocumentRealisation() {
        return new DocumentRealisation();
    }

    /**
     * Create an instance of {@link XmlVPPhraseSpec }
     * 
     */
    public XmlVPPhraseSpec createXmlVPPhraseSpec() {
        return new XmlVPPhraseSpec();
    }

    /**
     * Create an instance of {@link XmlStringElement }
     * 
     */
    public XmlStringElement createXmlStringElement() {
        return new XmlStringElement();
    }

    /**
     * Create an instance of {@link XmlSPhraseSpec }
     * 
     */
    public XmlSPhraseSpec createXmlSPhraseSpec() {
        return new XmlSPhraseSpec();
    }

}
