//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//


package simplenlg.xmlrealiser.wrapper;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for DocumentRealisation complex type.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>
 * &lt;complexType name="DocumentRealisation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Document" type="{https://github.com/simplenlg/simplenlg/tree/master/src/main/resources/xml}DocumentElement"/&gt;
 *         &lt;element name="Realisation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentRealisation", propOrder = {
    "document",
    "realisation"
})
public class DocumentRealisation {

    @XmlElement(name = "Document", required = true)
    protected XmlDocumentElement document;
    @XmlElement(name = "Realisation")
    protected String realisation;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDocumentElement }
     *     
     */
    public XmlDocumentElement getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDocumentElement }
     *     
     */
    public void setDocument(XmlDocumentElement value) {
        this.document = value;
    }

    /**
     * Gets the value of the realisation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealisation() {
        return realisation;
    }

    /**
     * Sets the value of the realisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealisation(String value) {
        this.realisation = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
