//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://simplenlg.googlecode.com/svn/trunk/res/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package simplenlg.xmlrealiser.wrapper;
