//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//


package simplenlg.xmlrealiser.wrapper;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for {@link simplenlg.features.DiscourseFunction}.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
 * &lt;simpleType name="discourseFunction"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AUXILIARY"/&gt;
 *     &lt;enumeration value="COMPLEMENT"/&gt;
 *     &lt;enumeration value="CONJUNCTION"/&gt;
 *     &lt;enumeration value="CUE_PHRASE"/&gt;
 *     &lt;enumeration value="FRONT_MODIFIER"/&gt;
 *     &lt;enumeration value="HEAD"/&gt;
 *     &lt;enumeration value="INDIRECT_OBJECT"/&gt;
 *     &lt;enumeration value="OBJECT"/&gt;
 *     &lt;enumeration value="PRE_MODIFIER"/&gt;
 *     &lt;enumeration value="POST_MODIFIER"/&gt;
 *     &lt;enumeration value="SPECIFIER"/&gt;
 *     &lt;enumeration value="SUBJECT"/&gt;
 *     &lt;enumeration value="VERB_PHRASE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "discourseFunction")
@XmlEnum
public enum XmlDiscourseFunction {

    AUXILIARY,
    COMPLEMENT,
    CONJUNCTION,
    CUE_PHRASE,
    FRONT_MODIFIER,
    HEAD,
    INDIRECT_OBJECT,
    OBJECT,
    PRE_MODIFIER,
    POST_MODIFIER,
    SPECIFIER,
    SUBJECT,
    VERB_PHRASE;

    public String value() {
        return name();
    }

    public static XmlDiscourseFunction fromValue(String v) {
        return valueOf(v);
    }

}
