//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//


package simplenlg.xmlrealiser.wrapper;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for {@link simplenlg.features.InterrogativeType}.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
 * &lt;simpleType name="interrogativeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HOW"/&gt;
 *     &lt;enumeration value="WHAT_OBJECT"/&gt;
 *     &lt;enumeration value="WHAT_SUBJECT"/&gt;
 *     &lt;enumeration value="WHERE"/&gt;
 *     &lt;enumeration value="WHO_INDIRECT_OBJECT"/&gt;
 *     &lt;enumeration value="WHO_OBJECT"/&gt;
 *     &lt;enumeration value="WHO_SUBJECT"/&gt;
 *     &lt;enumeration value="WHY"/&gt;
 *     &lt;enumeration value="YES_NO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "interrogativeType")
@XmlEnum
public enum XmlInterrogativeType {

    HOW,
    WHAT_OBJECT,
    WHAT_SUBJECT,
    WHERE,
    WHO_INDIRECT_OBJECT,
    WHO_OBJECT,
    WHO_SUBJECT,
    WHY,
    YES_NO;

    public String value() {
        return name();
    }

    public static XmlInterrogativeType fromValue(String v) {
        return valueOf(v);
    }

}
