//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//


package simplenlg.xmlrealiser.wrapper;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for {@link simplenlg.framework.LexicalCategory}.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
 * &lt;simpleType name="lexicalCategory"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ANY"/&gt;
 *     &lt;enumeration value="SYMBOL"/&gt;
 *     &lt;enumeration value="NOUN"/&gt;
 *     &lt;enumeration value="ADJECTIVE"/&gt;
 *     &lt;enumeration value="ADVERB"/&gt;
 *     &lt;enumeration value="VERB"/&gt;
 *     &lt;enumeration value="DETERMINER"/&gt;
 *     &lt;enumeration value="PRONOUN"/&gt;
 *     &lt;enumeration value="CONJUNCTION"/&gt;
 *     &lt;enumeration value="PREPOSITION"/&gt;
 *     &lt;enumeration value="COMPLEMENTISER"/&gt;
 *     &lt;enumeration value="MODAL"/&gt;
 *     &lt;enumeration value="AUXILIARY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "lexicalCategory")
@XmlEnum
public enum XmlLexicalCategory {

    ANY,
    SYMBOL,
    NOUN,
    ADJECTIVE,
    ADVERB,
    VERB,
    DETERMINER,
    PRONOUN,
    CONJUNCTION,
    PREPOSITION,
    COMPLEMENTISER,
    MODAL,
    AUXILIARY;

    public String value() {
        return name();
    }

    public static XmlLexicalCategory fromValue(String v) {
        return valueOf(v);
    }

}
